# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseapp.Lecturer'),
            preserve_default=False,
        ),
    ]
