# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseapp.Lecturer'),
            preserve_default=False,
        ),
    ]
