# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='course_id',
            new_name='course',
        ),
    ]
