VALIDATE_USER = '''
SELECT *
FROM USER
WHERE USERNAME = ?;
'''

SHOW_ALL_MOVIES = '''
SELECT *
FROM MOVIE;
'''

SELECT_PROJECTIONS_FOR_MOVIE = '''
SELECT *
FROM PROJECTION
WHERE MOVIE_ID = ?
ORDER BY DATE;
'''

GET_USER_ID_FROM_USERNAME = '''
SELECT ID
FROM USER
WHERE USERNAME = ?;
'''

GET_ALL_RESERVATIONS_FOR_PROJECTION = '''
SELECT *
FROM RESERVATION
WHERE PROJECTION_KEY = ?;
'''

GET_ALL_PROJECTIONS_RESERVATIONS_MOVIES_FOR_USER = '''
SELECT P.ID AS PROJECTION_ID, M.NAME AS MOVIE_NAME, P.DATE AS PROJECTION_DATE, P.TIME AS PROJECTION_TIME
FROM RESERVATION AS R
JOIN PROJECTION AS P
ON R.PROJECTION_KEY = P.ID
JOIN MOVIE AS M
ON P.MOVIE_ID = M.ID
WHERE R.USER_ID = ?
GROUP BY R.USER_ID, R.PROJECTION_KEY;
'''
